# ports: HOST:CONTAINER
version: '3.8'
services:
  xray:
    build: .
    container_name: xray-core
    restart: unless-stopped
    ports:
      - "9900:9900"
      - "9901:9901"
      - "9902:9902"
      - "9802:9802"