FROM hub.hamdocker.ir/golang as builder

WORKDIR /root/go/
COPY . .
RUN go get .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o xray-iran-bridge-updater .


FROM hub.hamdocker.ir/alpine:3.17

RUN wget https://github.com/XTLS/Xray-core/releases/download/v1.8.10/Xray-linux-64.zip
RUN unzip Xray-linux-64.zip -d /root/xray-core

WORKDIR /root/xray-core

COPY ./configs-node /root/xray-core/configs
COPY --chmod=777 ./rebootXray.sh /root/xray-core/rebootXray.sh
COPY --from=builder --chmod=777 /root/go/xray-iran-bridge-updater /root/xray-core/xray-iran-bridge-updater

CMD sh -c "/root/xray-core/xray-iran-bridge-updater && /root/xray-core/xray run -confdir /root/xray-core/configs"
#CMD ["/root/xray-core/xray-iran-bridge-updater", "&&" ,"/root/xray-core/xray", "run", "-confdir", "/root/xray-core/configs"]
