name: deploy-dockerized-run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    name: dev-deploy
    steps:
      - name: remove previous files
        uses: fifsky/ssh-action@master
        with:
          command: |
            cat ~/.ssh/authorized_keys
            ls -la ~/.ssh/
            cat > ~/.ssh/authorized_keys << EOF
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3Um9qshwrCE0FBUYvGipHedHBnTja3EeCEfoknD75A MMMohebi@outlook.com
            EOF
            cat ~/.ssh/authorized_keys
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
