name: deploy-dockerized-run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    name: dev-deploy
    steps:
      - name: remove previous files
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.DEPLOY_PATH}}
            rm -rf ..?* .[!.]* *
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}

      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{env.DEPLOY_PATH}}

  dockerized-and-run:
    needs: deploy
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    name: 'dockerized and run'
    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - name: run docker
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.DEPLOY_PATH}}
            cd ../
            docker compose --project-name v2ray-core up --build -d
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}