name: deploy-dockerized-run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    name: dev-deploy
    steps:
      - name: remove previous files
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo Hi
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
